# Generated by Django 3.1.4 on 2022-11-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glue', '0002_auto_20221110_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
