# Generated by Django 3.1.4 on 2022-11-10 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glue', '0003_new_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='work_desig_three',
            new_name='Work_desig_three',
        ),
    ]
