# Generated by Django 3.1.4 on 2022-11-10 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glue', '0004_auto_20221110_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='Work_desig_three',
        ),
        migrations.RemoveField(
            model_name='new',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='new',
            name='present_address',
        ),
    ]
