# Generated by Django 3.1.4 on 2022-11-23 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('glue', '0005_auto_20221110_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='user',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='new',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
